In [1]:
import numpy as np

# Numpy Exercises

In [2]:
# 1. Reverse a vector (first element becomes last) 

a = np.arange(50)
reverse_a = a[::-1]
print(reverse_a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [3]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8 

a = np.arange(9)
a = a.reshape(3,3)
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 3. Find indices of non-zero elements from [1,2,0,0,4,0]

a = np.array([1,2,0,0,4,0])
nz = np.nonzero(a)
print(nz)

(array([0, 1, 4]),)


In [5]:
# 4. Create a 10x10 array with random values and find the minimum and maximum values

a = np.random.random([10,10])
amin, amax = a.min(), a.max()
print(amin, amax)

0.009944936136906946 0.9762686569997564


In [6]:
# 5. Create a 2d array with 1 on the border and 0 inside 

z = np.ones((10,10))
z[1:-1,1:-1]=0
z


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
# 6. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [8]:
# 7. Create a checkerboard 8x8 matrix using the tile function

a = np.array([[0,1],[1,0]])
z = np.tile(a, (4,4))
print(z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
# 8. Normalize a 5x5 random matrix 

z = np.random.random((5,5))
norm_z = (z - np.mean(z))/np.std(z)
print(norm_z) 

[[ 0.19461322 -1.16391565 -1.439097    1.47060001  1.67353078]
 [ 0.395725   -0.52244098 -0.88686663  0.83336289 -0.518103  ]
 [-0.0730046  -0.31384612  0.6585167   0.55131148 -0.29509328]
 [-1.46247802 -0.52260415  2.00667364 -1.17553477 -0.53645492]
 [-0.03641939  0.65064136  1.92799369 -0.38353527 -1.03357498]]


In [10]:
# 9. Create random vector of size 10 and replace the maximum value by 0

a = np.random.random(10)
a[a.argmax()]=0
print(a)

[0.72932213 0.3838153  0.91886292 0.         0.95275204 0.16592855
 0.06210001 0.91675203 0.69062237 0.42022048]


In [11]:
# 10. Subtract the mean of each row of a matrix

Z = np.random.rand(5,10)
Y = Z - Z.mean(axis=1, keepdims=True)
print(Y)

[[ 0.06958802 -0.43552529  0.01253612  0.49678338  0.45430082  0.00958989
   0.03198802 -0.24530503 -0.25398668 -0.13996925]
 [-0.22793387 -0.05066614  0.36449569  0.45278593 -0.28236685 -0.14290571
  -0.23593162 -0.3629207   0.34289423  0.14254903]
 [ 0.14658765  0.06297023  0.28481265 -0.11389707 -0.28734692 -0.3383157
   0.25892647  0.3400749  -0.25270578 -0.10110644]
 [ 0.04600627  0.05886536  0.36194283  0.21935159 -0.18710806  0.0852089
  -0.1824298  -0.46751908  0.14058505 -0.07490308]
 [-0.45272757  0.01395613 -0.14592395 -0.12940633  0.3113081   0.19041888
   0.41572607 -0.56628718  0.16881723  0.19411861]]


In [12]:
# 11. How to tell if a given 2D array has null columns

z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False
